subjects=["C","C++","Java","Java Script","Python"]
print(subjects)
print(subjects[0])
print(subjects[2:])
print(subjects[-1:])
print("Python"in subjects)
print(subjects+["Data Structer",21])
print(subjects*2)
print(subjects)
print(subjects[0])
print(subjects[2:])
print(subjects[-1:])
print("Java"in subjects)
print(subjects+["C",33])
print(subjects*4)